# global filter; messages must have at least this severity to pass:
minSeverity: Debug

# global file rotation settings:
rotation:
  rpLogLimitBytes: 5000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK

# if wanted, the GUI is listening on this port:
#hasGUI: 12871

# if wanted, the EKG interface is listening on this port:
#hasEKG: 12781


# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: FileSK
    scName: "logs/node-0.log"
    scFormat: ScText
  - scKind: StdoutSK
    scName: stdout
    scFormat: ScText
    scRotation: null

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - FileSK
    - "logs/node-0.log"
  - - StdoutSK
    - stdout

# more options which can be passed as key-value pairs:
options:
  cfokey:
    value: "Release-1.0.0"
  mapSubtrace:
    '#ekgview':
      contents:
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: .monoclock.basic.
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.cpuNs.timed.
      - - tag: StartsWith
          contents: '#ekgview.#aggregation.cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.gcNum.timed.
      subtrace: FilterTrace
    'cardano.epoch-validation.utxo-stats':
      # Change the `subtrace` value to `Neutral` in order to log
      # `UTxO`-related messages during epoch validation.
      subtrace: NoTrace
  mapBackends:
    cardano.node.metrics.ChainDB:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.metrics.Forge:
      - EKGViewBK
    cardano.node.metrics.Mempool:
      - EKGViewBK
    cardano.node.metrics:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.peers:
      - EKGViewBK
    cardano.node.BlockFetchDecision.peers:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend


##########################################################
############### Cardano Node Configuration ###############
##########################################################


NodeId: 0
Protocol: MockedBFT
NumCoreNodes: 1
RequiresNetworkMagic: RequiresMagic
PBftSignatureThreshold:
TurnOnLogging: True
ViewMode: SimpleView
TurnOnLogMetrics: True
SlotDuration: 5
SnapshotsOnDisk: 60
SnapshotInterval: 60
BlockchainBlockFetchInterval: 5000000
RpcUrl: http://127.0.0.1:8546
PrometheusPort: 13788

# Checkpointing parameters
CheckpointInterval: 4
RequiredMajority: 1
FedPubKeys:
  - ec33a3689573db2f4db4586bb7089cda045116a21cce20c9a6fe7ccadcf9fb336075b3644ac9f0a20e6d45a9e99db477cc420d050969f2d8bfb7408b2169b167
NodePrivKeyFile: /home/ninjatrappeur/Code/tweag/iohk/blockchain/obft/blockchain-checkpoint-node/configuration/privkey


#####    Update Parameters    #####

ApplicationName: blockchain-checkpoint
ApplicationVersion: 1
LastKnownBlockVersion-Major: 0
LastKnownBlockVersion-Minor: 2
LastKnownBlockVersion-Alt: 0
minSeverity: Debug

# global file rotation settings:
rotation:
  rpLogLimitBytes: 5000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

#####         Tracing         #####

# MinimalVerbosity: Minimal level of the rendering of captured items
# MaximalVerbosity: Maximal level of the rendering of captured items
# NormalVerbosity: the default level of the rendering of captured items
TracingVerbosity: NormalVerbosity

# Trace BlockFetch client.
TraceBlockFetchClient: True

# Trace BlockFetch decisions made by the BlockFetch client.
TraceBlockFetchDecisions: True

# Trace BlockFetch protocol messages.
TraceBlockFetchProtocol: True

# Serialised Trace BlockFetch protocol messages.
TraceBlockFetchProtocolSerialised: False

# Trace BlockFetch server.
TraceBlockFetchServer: True

# Verbose tracer of ChainDB
TraceChainDb: True

# Trace ChainSync client.
TraceChainSyncClient: True

# Trace ChainSync server (blocks).
TraceChainSyncBlockServer: True

# Trace ChainSync server (headers)
TraceChainSyncHeaderServer: True

# Trace ChainSync protocol messages.
TraceChainSyncProtocol: True

# Trace DNS Resolver messages.
TraceDNSResolver: False

# Trace DNS Subscription messages.
TraceDNSSubscription: False

# Trace error policy resolution.
TraceErrorPolicy: False

# Trace block forging.
TraceForge: True

# Trace IP Subscription messages.
TraceIpSubscription: False

# Trace local ChainSync protocol messages.
TraceLocalChainSyncProtocol: True

# Trace local TxSubmission protocol messages.
TraceLocalTxSubmissionProtocol: True

# Trace local TxSubmission server.
TraceLocalTxSubmissionServer: True

# Trace mempool.
TraceMempool: True

# Trace Mux Events
TraceMux: False

# Trace TxSubmission server (inbound transactions).
TraceTxInbound: True

# Trace TxSubmission client (outbound transactions).
TraceTxOutbound: True

# Trace TxSubmission protocol messages.
TraceTxSubmissionProtocol: True
