##########################################################
################### Node Configuration ###################
##########################################################


NodeId: 0
Protocol: MockedBFT
NumCoreNodes: 1
NetworkMagic : 12345
SecurityParam : 3
TurnOnLogging: True
SlotDuration: 5
SnapshotsOnDisk: 60
SnapshotInterval: 60
PoWBlockFetchInterval: 5000000
PoWNodeRpcUrl: http://127.0.0.1:8546
PrometheusPort: 13788
SystemStart: "2021-03-26T12:00:00Z"

# Checkpointing parameters
CheckpointInterval: 4
RequiredMajority: 1
FedPubKeys:
  - ec33a3689573db2f4db4586bb7089cda045116a21cce20c9a6fe7ccadcf9fb336075b3644ac9f0a20e6d45a9e99db477cc420d050969f2d8bfb7408b2169b167
NodePrivKeyFile: morpho-checkpoint-node/tests/configuration/Golden/secret-key-normal
StableLedgerDepth: 6
DatabaseDirectory: db
NodePort: 1234

TopologyFile: configuration/morpho-topology.json

##### LoggingFeature Configuration #####

Logging:

  minSeverity: Info

  # EKG is a simple metrics monitoring system. Uncomment the following to listen
  # on the given local port and point your web browser to http://localhost:12788/
  # for a live view. The same URL can also serve JSON output.
  # hasEKG: 12788

  # The Prometheus monitoring system can also be used. Uncomment the following
  # to listen on the given port
  # hasPrometheus: 12789

  # For the Katip logging backend we must set up outputs (called scribes)
  # The available types of scribe are:
  #   FileSK for files
  #   StdoutSK/StdoutSK for stdout/stderr
  #   JournalSK for systemd's journal system
  #   DevNullSK
  # The scribe output format can be ScText or ScJson. Log rotation settings can
  # be specified in the defaults below or overidden on a per-scribe basis here.
  setupScribes:
    - scKind: FileSK
      scName: "logs/staging.log"
      scFormat: ScText

    - scKind: StdoutSK
      scName: stdout
      scFormat: ScText
      scRotation: null

  # For the Katip logging backend this specifies the default scribes that trace
  # output is sent to if it is not configured to be sent to other scribes.
  defaultScribes:
    - - FileSK
      - "logs/staging.log"

    - - StdoutSK
      - stdout

  setupBackends:
    - KatipBK

  defaultBackends:
    - KatipBK

  ##### Fine grained logging control #####
  options:
    mapBackends:
